// examples/simple-counter/src/Counter.tsx
import { Button, Span } from "reaccord"
import { useState } from "react"

type CounterProps = {
  start?: number
}

export const Counter = ({ start = 0 }: CounterProps) => {
  const [count, setCount] = useState(start)

  return (
    <>
      <Span bold>{count}</Span>
      <Button onClick={() => setCount(count + 1)}>+</Button>
    </>
  )
}

// apps/solid-example/src/Counter/index.tsx
import { createSignal } from "solid-js"

export const Counter = () => {
    const [count, setCount] = createSignal(0)

    return (
        <>
            <content>
                <span bold>reaccord/solid counter</span>
            </content>
            <action-row>
                <button
                    id="add"
                    style="Danger"
                    onClick={() => {
                        setCount((count) => count - 1)
                    }}
                >
                    -
                </button>
                <button style="Secondary" disabled>
                    {count()}
                </button>
                <button
                    id="sub"
                    style="Success"
                    onClick={() => {
                        setCount((count) => count + 1)
                    }}
                >
                    +
                </button>
            </action-row>
        </>
    )
}
